import type { Property } from "@/components/property-card"

export const WILAYAS = [
  "Alger", "Oran", "Constantine", "Annaba", "Sétif", "Blida", "Béjaïa",
  "Tlemcen", "Tizi Ouzou", "Batna", "Biskra", "Tamanrasset", "Ghardaïa",
  "Skikda", "Jijel", "Tipaza", "Boumerdès", "Médéa", "Chlef", "Mostaganem",
]

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "Appartement vue mer à Alger Centre",
    location: "Hydra",
    wilaya: "Alger",
    price: 8500,
    rating: 4.9,
    reviewCount: 47,
    image: "/images/property-1.jpg",
    type: "Appartement",
    bedrooms: 3,
    guests: 6,
    amenities: ["wifi", "ac", "parking", "tv", "kitchen"],
    isNew: false,
  },
  {
    id: "2",
    title: "Villa traditionnelle avec piscine – Tlemcen",
    location: "Tlemcen",
    wilaya: "Tlemcen",
    price: 15000,
    rating: 4.8,
    reviewCount: 32,
    image: "/images/property-2.jpg",
    type: "Villa",
    bedrooms: 5,
    guests: 10,
    amenities: ["wifi", "pool", "parking", "kitchen", "balcony"],
    isNew: false,
  },
  {
    id: "3",
    title: "Maison de plage luxueuse – Béjaïa",
    location: "Bejaia",
    wilaya: "Béjaïa",
    price: 12000,
    rating: 5.0,
    reviewCount: 18,
    image: "/images/property-3.jpg",
    type: "Villa",
    bedrooms: 4,
    guests: 8,
    amenities: ["wifi", "pool", "ac", "kitchen", "balcony"],
    isNew: true,
  },
  {
    id: "4",
    title: "Chalet de montagne – Tikjda",
    location: "Tikjda",
    wilaya: "Bouira",
    price: 6500,
    rating: 4.7,
    reviewCount: 24,
    image: "/images/property-4.jpg",
    type: "Chalet",
    bedrooms: 3,
    guests: 7,
    amenities: ["wifi", "kitchen", "parking", "tv"],
    isNew: false,
  },
  {
    id: "5",
    title: "Tente Saharienne de Luxe – Tamanrasset",
    location: "Tamanrasset",
    wilaya: "Tamanrasset",
    price: 9000,
    rating: 4.9,
    reviewCount: 11,
    image: "/images/property-5.jpg",
    type: "Tente de luxe",
    bedrooms: 1,
    guests: 2,
    amenities: ["wifi", "ac"],
    isNew: true,
  },
  {
    id: "6",
    title: "Studio moderne – Centre d'Alger",
    location: "Ben Aknoun",
    wilaya: "Alger",
    price: 4500,
    rating: 4.6,
    reviewCount: 63,
    image: "/images/property-6.jpg",
    type: "Studio",
    bedrooms: 1,
    guests: 2,
    amenities: ["wifi", "ac", "tv", "kitchen"],
    isNew: false,
  },
]

export const MOCK_REVIEWS = [
  {
    id: "1",
    user: "Amira B.",
    avatar: "A",
    rating: 5,
    date: "Janvier 2025",
    comment:
      "Séjour absolument parfait ! Le logement était impeccable, exactement comme sur les photos. L'hôte était très réactif et serviable.",
  },
  {
    id: "2",
    user: "Karim D.",
    avatar: "K",
    rating: 4,
    date: "Décembre 2024",
    comment:
      "Très bel appartement dans un quartier calme. La vue est magnifique. Quelques petits détails à améliorer mais globalement excellent.",
  },
  {
    id: "3",
    user: "Yasmine M.",
    avatar: "Y",
    rating: 5,
    date: "Novembre 2024",
    comment: "Je recommande vivement ce logement ! L'emplacement est idéal, propre et bien équipé. On reviendra sûrement.",
  },
]
